### ISSUE TITLE
People URL

### ISSUE THREAD

**Issue by GezimSejdiu** [SmartDataAnalytics/sda.tech#17]
Each group of people based on their position should have their own URL (like instead of just having http://sda.tech/people/# we should be able to go directly to PhD Students for instance: http://sda.tech/people/phdStudent/# .

**Comment by RohanAsmat** [comment]
This is partially done, for some pages and currently under dev for the left ones!

**Comment by GezimSejdiu** [comment]
@RohanAsmat @AdrianBajraktari 
Just to have it as an information (found by Günter). There is a bug when you want to go back from a people profile page.  
#### How to reproduce it : 
Go to a profile page (e.g. http://sda.tech/Person/GezimSejdiu/ ) --> click to go back, you will end up having this message `502 Bad Gateway` and it will redirect to http://sda.tech/people/Professors#, which shouldn't be the case.

Best,
