### ISSUE TITLE
Add possibility to list all the SDA members

### ISSUE THREAD

**Issue by GezimSejdiu** [SmartDataAnalytics/sda.tech#21]
The tabs for people is fine to have it but will prefer to list all the members (grouped by their position title) on a single page, like we do have on our WordPress site: http://sda.cs.uni-bonn.de/people/ .

If someone outside form our group would like to see the list of all the members then he/she would like to have it in one place.

**Comment by RohanAsmat** [comment]
I agree with this, I think this is also a UX flaw as it is being done for other pages but not for this one!
