### ISSUE TITLE
Make pillars aligned horizontally 

### ISSUE THREAD

**Issue by GezimSejdiu** [SmartDataAnalytics/sda.tech#23]
Would have been great if we can manage somehow that the pillars on the front page to be aligned horizontally instead of vertical alignment since the user will not need to scroll a lot through the page but will have them at one place (see http://sda.cs.uni-bonn.de/ as a template).

Of course, it will be a challenge to fit the icon, text and the leader(s) on the single pillar but somehow we can shrink a bit and make it visible horizontally.

**Comment by AdrianBajraktari** [comment]
There is one pillar below all the other ones, but when Deep Learning is removed (and KEV becomes Smart Services), it will all fit in one line. Otherwise, I just changed the Group Leaders styles a bit, so it does not glitch around.
I hope this somehow resembles the idea you had in mind.

**Comment by GezimSejdiu** [comment]
Hi @AdrianBajraktari ,
many thanks for your work. But still, I'm not satisfied with the view. It should be auto size with the width of the page, does not matter how many pillars we do have (even they may look a bit small). And one more thing, can we align the text `center` and maybe (it is just my opinion) remove the background color on the icon and the name of the group. 
Best,

**Comment by AdrianBajraktari** [comment]
Hi @GezimSejdiu ,
regarding the changes to icon and text alignment, there is no problem with that (although I actually like the current design). But making the pillars auto size according to page width would eventually end up in either very thin pillars (and therefore very few words per line) if we only auto size the width of the pillars, or in very small pillars in general, when resizing width and height, which might look out of proportion with respect to the rest of the page. When adjusting width and height, we eventually also have to adjust the text size - resulting in perhaps barely readable text.

**Comment by GezimSejdiu** [comment]
Agree! But again, we could save some space by removing `Specialized Groups Working under SDA` since it is obvious that those pillars represent subgroups/topics withing SDA and fit them with that div. As you can see there is a space between the margins and we could basically have more space by removing that different. And reg. the text alignment, I again will vote for `center` (it is more readable -- at least for me :) ). But better you and @RohanAsmat  decide what is best for UX/:)
