### ISSUE TITLE
Home Page Improvement

### ISSUE THREAD

**Issue by JensLehmann** [SmartDataAnalytics/sda.tech#27]
On http://sda.tech, there should be more than just a static image, e.g. 3-4 sliding images.

**Comment by JensLehmann** [comment]
We might also consider reducing the image height as this takes away quite some space such that in most viewers, only parts of the image may be visible without scrolling.

**Comment by RohanAsmat** [comment]
Sure its actually a slider but I think we are lacking images so I will update this!

**Comment by AdrianBajraktari** [comment]
In addition to make the slider a bit smaller, we should give it a static height so that the text underneath it does not move up and down when the images change.

**Comment by AdrianBajraktari** [comment]
So just to point it out: I already changed it to have a static height. Is the height good this way or should I reduce it even further? This would also mean that we need to shrink the width of the slider, which might not look good in direct comparison with the width of the text box right underneath it.

**Comment by RohanAsmat** [comment]
@AdrianBajraktari for me it looks pretty good, but I think you also reduced the transition rate is it right?
because in this way I am missing out the transitory images! 
If you didn't maybe we can increase the animation rate!
