### ISSUE TITLE
Profile pictures--Compressed

### ISSUE THREAD

**Issue by S6savahd** [SmartDataAnalytics/sda.tech#33]
Some of the profile pictures look compressed. An important example is the one for Jens, that does not look nice!

**Comment by JensLehmann** [comment]
http://sda.tech/Person/SteffenLohmann/ is even worse ... I think this issue as been reported several times. Just please do not change height and width of pictures at the same time. Rather prepare the pictures properly in any graphics program.

**Comment by AdrianBajraktari** [comment]
Took a short test on this issue today. The easiest way would be to have the images of people, projects and partners as background-images of a <div> instead of having them as src of <img>. Then, we could center and "cut" them with background-attributes very easily.

**Comment by RohanAsmat** [comment]
@AdrianBajraktari right but I think the best solution is to probably have them all of equal resolution!
