### ISSUE TITLE
Captions for PLUS sign in the index page

### ISSUE THREAD

**Issue by S6savahd** [SmartDataAnalytics/sda.tech#34]
The plus sign in the main page is nice, however, it has three shortcuts: to the blog, to the same page and to the map showing our address. First, redirecting to the same page does not make sense, the second I would add labels when someone hovers on these icons, it should show where I will end up after clicking on them. For example with wifi sign, I would never guess I will end up in the blog, if there would be a text popping up by hovering the mouse on that would make it much easier.

**Comment by RohanAsmat** [comment]
tool tips added, for adding the homepage icon the idea was easy access to homepage from anyother pages such as 

- Teaching
Courses

**Comment by geraltofrivia** [comment]
Would want to point out that the RSS icon does not necessarily invoke `Blog`, and the address too would be better demarcated with a map icon (e.g. [this](https://icons8.com/icon/47789/map))
