### ISSUE TITLE
Missing values for Social profiles

### ISSUE THREAD

**Issue by GezimSejdiu** [SmartDataAnalytics/sda.tech#40]
As some of the members may not have all the social profiles defined to be shown on the profile page, would be great to make it more dynamic which lists only those which are listed on the Person card/entry.
  - http://sda.tech/Person/GezimSejdiu/ -- if you click on the facebook icon it will open an instance of the same page, but would have been better if we hide it and list other profiles which are linked on my profile (e.g. [Twitter](https://github.com/SmartDataAnalytics/sda.tech/blob/develop/rdf-data/sda.tech.ttl#L348)).

**Comment by RohanAsmat** [comment]
Sure thats true some conditions have been missing, plus I guess we can also include research gate?

**Comment by AdrianBajraktari** [comment]
RG needs an icon, though.
