### ISSUE TITLE
Navigation Menu Entries

### ISSUE THREAD

**Issue by vitalis-wiens** [SmartDataAnalytics/sda.tech#41]
The navigation menu entries are not vertically aligned in the center

**Comment by vitalis-wiens** [comment]
additionally, the behaviour of  the navigation menu based on the width on the homepage is not optimal

**Comment by RohanAsmat** [comment]
Thank you for information, fix for earlier issue on the feature branch! 
Refer to Issue #50, for Mobile based user experiences!
