### ISSUE TITLE
Images on Title Page

### ISSUE THREAD

**Issue by vitalis-wiens** [SmartDataAnalytics/sda.tech#42]
*The transition takes to long
*The animation is somehow not smooth
*There are no control buttons to be able to switch between images

**Comment by vitalis-wiens** [comment]
caption of the images 2 and 3 are called "Caption Two" and "Caption Three" 

can we also remove the selection on the caption of the image and the number of images
In WebVOWL I use this class for no select, found it somewhere at StackOverflow

.noselect {
	-webkit-touch-callout: none; /* iOS Safari */
	-webkit-user-select: none; /* Safari */
	-khtml-user-select: none; /* Konqueror HTML */
	-moz-user-select: none; /* Firefox */
	-ms-user-select: none; /* Internet Explorer/Edge */
	user-select: none; /* Non-prefixed version, currently
                                  supported by Chrome and Opera */
}

**Comment by RohanAsmat** [comment]
Fixed apart from controls, for that we may introduce a new widget later!
