### ISSUE TITLE
Plus button right lower corner

### ISSUE THREAD

**Issue by vitalis-wiens** [SmartDataAnalytics/sda.tech#43]
I think the size of this button is to large, on mobile devices it takes like 1/6 of the screen space

can we make it smaller when it is collapsed?

**Comment by RohanAsmat** [comment]
@vitalis-wiens Sure, 
One question are the icons like blog link etc. are also appearing in collapsed state?

**Comment by vitalis-wiens** [comment]
No, they do behave as intended :)

**Comment by RohanAsmat** [comment]
Taking out plus button!
