### ISSUE TITLE
Update to 3.0.0

### ISSUE THREAD

**Issue by white-gecko** [SmartDataAnalytics/sda.tech#56]
In the Gemfile.lock you are on 2.3.0

https://github.com/SmartDataAnalytics/sda.tech/blob/052edefcc5a951f341d0e4c460827594d52dcd63/Gemfile.lock#L58

I've released a new major update of jekyll-rdf to 3.0.0 could you please try locally if things are breaking or if everything is fine?

**Comment by white-gecko** [comment]
For instance this failure: https://travis-ci.org/SmartDataAnalytics/sda.tech/builds/444992903 is due to a breaking change which interprets the prefix file paths relative to the source directory, not to rdf-data anymore. So you can also move the prefixes and the RDF-file to `_data`.

**Comment by RohanAsmat** [comment]
@NargisTahara

**Comment by RohanAsmat** [comment]
![screenshot from 2018-10-24 12-40-35](https://user-images.githubusercontent.com/7516846/47425246-0ab6a200-d78a-11e8-9454-53a49133237b.png)

Even after moving rdf-data and prefix file to _data, I am getting the same error locally!

**Comment by white-gecko** [comment]
You have to change the `rdf_prefix_path` specifications in the layout files, as I've shown in the pullrequest

**Comment by RohanAsmat** [comment]
thanks, I just saw it !

**Comment by white-gecko** [comment]
But still this is failing due to some strange situation.

**Comment by white-gecko** [comment]
Can you please try the built with the current prerelease?

**Comment by white-gecko** [comment]
@RohanAsmat could you please locally checkout this pullrequest https://github.com/white-gecko/jekyll-rdf/pull/225 and check if it fixes our problem?
