### ISSUE TITLE
Jekyll-RDF Plugin Update Error and Warnings 

### ISSUE THREAD

**Issue by RohanAsmat** [SmartDataAnalytics/sda.tech#6]
After updating the bundle and specifically jekyll-rdf-plugin, fatal warnings and error appears which needs to be resolved.

**Comment by white-gecko** [comment]
Is this related to jekyll-rdf or to something else?

**Comment by RohanAsmat** [comment]
They were because of updation of  Jekyll-RDF, but not because of Jekyll-RDF. Their were errors on the client side specifically to the ttl. Fixing it resolved the issue.
