### ISSUE TITLE
Teaching courses do not load

### ISSUE THREAD

**Issue by JensLehmann** [SmartDataAnalytics/sda.tech#64]
There is still this bug there: http://sda.tech/Course/LabNaturalLanguageProcessingWinter2017/

Go on http://sda.tech/Course/wintersemeter/ and click on “Seminar Natural Language Processing” to reproduce.

**Comment by GezimSejdiu** [comment]
Fixed by [#e58efd9](https://github.com/SmartDataAnalytics/sda.tech/commit/e58efd9d9208a0f695004c08f29492507d32b849)
