### ISSUE TITLE
Emails not as text

### ISSUE THREAD

**Issue by np00** [SmartDataAnalytics/sda.tech#8]
To reduce the amount of spam on your mail account, it would be nice if the emails on the homepage are presented as images or something similar.

**Comment by steffen-l** [comment]
Images are also not ideal. I would rather suggest to go for a javascript-based text-based email composition. There are js-based solutions to avoid spam.

**Comment by GezimSejdiu** [comment]
Indeed, I also do not prefer using images. On our wordpress site we use [javascript-based email address encoder](https://wordpress.org/plugins/email-address-encoder/) . We could check how they did and apply the same pattern :)

**Comment by steffen-l** [comment]
I integrated SpamSpan on my personal homepage some time ago: http://www.spamspan.com . It is easy and elegant and has different "paranoia" levels - from simple CSS to more JS-based spam blockers (even one non-intrusive one with an @-symbol image for Niklas ;-) ).

**Comment by RohanAsmat** [comment]
Solved the issue using the [Jekyll Email Protect](https://github.com/vwochnik/jekyll-email-protect) plugin.
